using Microsoft.Win32;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Input;
using System.Windows.Media.Effects;
using MonoTorrent;
using MonoTorrent.Client;
using MonoTorrent.TrackerServer;
using MonoTorrent.Connections.TrackerServer;
using Forms = System.Windows.Forms;
using Drawing = System.Drawing;

namespace LanControlWpf
{
    public partial class MainWindow : Window
    {
        const int DiscoveryPort = 45670, CommandPort = 45671; const string Magic = "LAN_CONTROL_TOOL_V1";
        readonly ObservableCollection<DeviceInfo> devices = new ObservableCollection<DeviceInfo>(); readonly ObservableCollection<DistributionTask> distributionTasks = new ObservableCollection<DistributionTask>(); readonly ObservableCollection<SavedIpProfile> ipProfiles=new ObservableCollection<SavedIpProfile>(); readonly ObservableCollection<NetworkAdapterOption> networkAdapters=new ObservableCollection<NetworkAdapterOption>(); readonly ConcurrentDictionary<string, DeviceInfo> deviceMap = new ConcurrentDictionary<string, DeviceInfo>();
        Settings settings; CancellationTokenSource cancel; UdpClient udp; TcpListener listener; readonly JavaScriptSerializer json = new JavaScriptSerializer(); readonly object logLock = new object(); readonly object settingsLock = new object(); readonly List<string> logs = new List<string>(); Forms.NotifyIcon trayIcon; ClientEngine torrentEngine; TrackerServer torrentTracker; ITrackerListener torrentTrackerListener; TcpListener distributionMetadataListener; readonly ConcurrentDictionary<string,DistributionTask> distributionMap=new ConcurrentDictionary<string,DistributionTask>(); readonly ConcurrentDictionary<string,TorrentManager> distributionManagers=new ConcurrentDictionary<string,TorrentManager>(); readonly ConcurrentDictionary<string,ConcurrentDictionary<string,DistributionPeerStatus>> distributionPeers=new ConcurrentDictionary<string,ConcurrentDictionary<string,DistributionPeerStatus>>(); bool settingsRecoveredFromBackup; bool settingsNeedsInitialSave; string settingsLoadWarning; string settingsSaveError;
        sealed class CommandResult { public DeviceInfo Device; public bool Success; public string Message; }
        [DllImport("iphlpapi.dll",ExactSpelling=true)] static extern int SendARP(int destinationIp,int sourceIp,byte[] macAddress,ref int physicalAddressLength);
        string SettingsPath { get { return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "LanControlTool", "settings.json"); } }
        string SettingsBackupPath { get { return SettingsPath + ".bak"; } }
        string DefaultLogFolder { get { return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "LanControlTool", "Logs"); } }
        string DefaultDistributionFolder { get { return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "LanControlTool", "Downloads"); } }
        public MainWindow() { InitializeComponent(); DeviceGrid.ItemsSource = devices; DistributionTaskList.ItemsSource=distributionTasks; IpProfileList.ItemsSource=ipProfiles; NetworkAdapterBox.ItemsSource=networkAdapters; settings = LoadSettings(); LoadSavedDevices(); LoadIpProfiles(); UsernameBox.Text = settings.Username; PasswordBox.Password = settings.Password; AppPathBox.Text = settings.AppPath; BatPathBox.Text = settings.BatPath; LogFolderBox.Text = settings.LogFolder; DistributionFolderBox.Text=settings.DistributionFolder; AllowCheck.IsChecked = settings.AllowRemote; AutoHideCheck.IsChecked = settings.AutoHide; RefreshNetworkAdapters(); SetupTray(); Loaded += delegate { StartNetwork(); if(!string.IsNullOrWhiteSpace(settingsLoadWarning)) Dispatcher.BeginInvoke(new Action(()=>MessageBox.Show(settingsLoadWarning,"配置恢复",MessageBoxButton.OK,MessageBoxImage.Warning))); if(settings.AutoHide) Dispatcher.BeginInvoke(new Action(()=>WindowState=WindowState.Minimized)); }; StateChanged += MainWindow_StateChanged; Closing += delegate { StopNetwork(); if(trayIcon!=null) trayIcon.Dispose(); }; }
        Settings CreateDefaultSettings() { return new Settings { DeviceId = Guid.NewGuid().ToString("N"), Username = Environment.UserName, LogFolder=DefaultLogFolder, DistributionFolder=DefaultDistributionFolder, Devices = new List<SavedDevice>(), IpProfiles=new List<SavedIpProfile>() }; }
        Settings NormalizeSettings(Settings value) { if(value==null)throw new SerializationException("配置内容为空"); if(string.IsNullOrWhiteSpace(value.DeviceId))value.DeviceId=Guid.NewGuid().ToString("N"); if(string.IsNullOrWhiteSpace(value.Username))value.Username=Environment.UserName; if(string.IsNullOrWhiteSpace(value.LogFolder))value.LogFolder=DefaultLogFolder; if(string.IsNullOrWhiteSpace(value.DistributionFolder))value.DistributionFolder=DefaultDistributionFolder; if(value.Devices==null)value.Devices=new List<SavedDevice>(); if(value.IpProfiles==null)value.IpProfiles=new List<SavedIpProfile>(); return value; }
        Settings ReadSettingsFile(string path) { using(var stream=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.Read)) return NormalizeSettings((Settings)new DataContractJsonSerializer(typeof(Settings)).ReadObject(stream)); }
        Settings LoadSettings() { Directory.CreateDirectory(Path.GetDirectoryName(SettingsPath)); Exception primaryError=null; if(File.Exists(SettingsPath))try{return ReadSettingsFile(SettingsPath);}catch(Exception ex){primaryError=ex;} if(File.Exists(SettingsBackupPath))try{var recovered=ReadSettingsFile(SettingsBackupPath); settingsRecoveredFromBackup=true; settingsLoadWarning="主配置文件损坏，已自动使用备份恢复。原损坏文件会被保留，保存设置后将生成新的主配置。"; return recovered;}catch{} if(primaryError!=null)settingsLoadWarning="配置文件无法读取，且没有可用备份。程序暂时使用默认配置；请重新确认远程控制和应用路径后保存。\n\n原因："+primaryError.Message; else settingsNeedsInitialSave=true; return CreateDefaultSettings(); }
        bool SaveSettingsFile() { lock(settingsLock) { string temporaryPath=null; try { var folder=Path.GetDirectoryName(SettingsPath); Directory.CreateDirectory(folder); settings.Devices=deviceMap.Values.Select(d=>new SavedDevice { DeviceId=d.DeviceId,Username=d.Username,IP=d.IP,Mac=d.Mac,AllowRemote=d.AllowRemote,HasApp=d.HasApp,HasBat=d.HasBat,LastSeen=d.LastSeen }).ToList(); settings.IpProfiles=ipProfiles.ToList(); var selectedAdapter=NetworkAdapterBox==null?null:NetworkAdapterBox.SelectedItem as NetworkAdapterOption; if(selectedAdapter!=null)settings.LastNetworkAdapterId=selectedAdapter.Id; temporaryPath=Path.Combine(folder,"settings."+Process.GetCurrentProcess().Id+"."+Guid.NewGuid().ToString("N")+".tmp"); using(var stream=new FileStream(temporaryPath,FileMode.CreateNew,FileAccess.Write,FileShare.None)) { new DataContractJsonSerializer(typeof(Settings)).WriteObject(stream,settings); stream.Flush(true); } if(settingsRecoveredFromBackup) { if(File.Exists(SettingsPath)) { var corruptPath=SettingsPath+".corrupt-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N").Substring(0,6); File.Move(SettingsPath,corruptPath); } File.Move(temporaryPath,SettingsPath); settingsRecoveredFromBackup=false; } else if(File.Exists(SettingsPath)) File.Replace(temporaryPath,SettingsPath,SettingsBackupPath,true); else File.Move(temporaryPath,SettingsPath); settingsSaveError=null; return true; } catch(Exception ex) { settingsSaveError=ex.Message; try { if(!string.IsNullOrWhiteSpace(temporaryPath)&&File.Exists(temporaryPath))File.Delete(temporaryPath); } catch{} Debug.WriteLine("保存配置失败："+ex); return false; } } }
        void LoadSavedDevices() { foreach(var d in settings.Devices) if(!string.IsNullOrWhiteSpace(d.DeviceId)) deviceMap[d.DeviceId]=new DeviceInfo { DeviceId=d.DeviceId, Username=d.Username, IP=d.IP, Mac=d.Mac, AllowRemote=d.AllowRemote, HasApp=d.HasApp, HasBat=d.HasBat, LastSeen=d.LastSeen, IsOnline=false }; }
        void LoadIpProfiles() { ipProfiles.Clear(); foreach(var profile in settings.IpProfiles.Where(x=>x!=null&&!string.IsNullOrWhiteSpace(x.IPAddress))) { if(string.IsNullOrWhiteSpace(profile.Id))profile.Id=Guid.NewGuid().ToString("N"); if(string.IsNullOrWhiteSpace(profile.Name))profile.Name=profile.IPAddress; ipProfiles.Add(profile); } }
        void SetupTray() { trayIcon=new Forms.NotifyIcon { Icon=Drawing.SystemIcons.Application, Text="局域网控制工具", Visible=true }; var menu=new Forms.ContextMenuStrip(); menu.Items.Add("显示主窗口",null,delegate { ShowFromTray(); }); menu.Items.Add("退出",null,delegate { trayIcon.Visible=false; Close(); }); trayIcon.ContextMenuStrip=menu; trayIcon.DoubleClick += delegate { ShowFromTray(); }; }
        void MainWindow_StateChanged(object sender, EventArgs e) { if(WindowState==WindowState.Minimized) { Hide(); if(trayIcon!=null) trayIcon.ShowBalloonTip(1500,"局域网控制工具","程序仍在后台运行。双击托盘图标可恢复窗口。",Forms.ToolTipIcon.Info); } }
        void ShowFromTray() { Show(); WindowState=WindowState.Normal; Activate(); }
        void StartNetwork() { try { cancel = new CancellationTokenSource(); udp = new UdpClient(DiscoveryPort); udp.EnableBroadcast = true; listener = new TcpListener(IPAddress.Any, CommandPort); listener.Start(); if(settingsNeedsInitialSave){settingsNeedsInitialSave=!SaveSettingsFile();} _ = ReceiveAnnouncements(cancel.Token); _ = AcceptCommands(cancel.Token); _ = BroadcastLoop(cancel.Token); _ = CleanupLoop(cancel.Token); Broadcast(); SetStatus(""); Log("服务已启动"); } catch (Exception ex) { SetStatus("服务启动失败，请检查端口与防火墙"); MessageBox.Show(ex.Message, "启动失败", MessageBoxButton.OK, MessageBoxImage.Error); } }
        void StopNetwork() { try { if (cancel != null) cancel.Cancel(); if (udp != null) udp.Close(); if (listener != null) listener.Stop(); if(distributionMetadataListener!=null)distributionMetadataListener.Stop(); if(torrentEngine!=null)torrentEngine.StopAllAsync().Wait(2000); if(torrentTracker!=null)torrentTracker.Dispose(); } catch { } }
        bool TryReadAnnouncementBool(Dictionary<string,object> announcement,string key,out bool value) { value=false; object raw; if(!announcement.TryGetValue(key,out raw)||raw==null)return false; if(raw is bool){value=(bool)raw;return true;} return bool.TryParse(Convert.ToString(raw),out value); }
        async Task ReceiveAnnouncements(CancellationToken token) { while (!token.IsCancellationRequested) try { var r = await udp.ReceiveAsync(); var a = json.Deserialize<Dictionary<string, object>>(Encoding.UTF8.GetString(r.Buffer)); if (!a.ContainsKey("magic") || Convert.ToString(a["magic"]) != Magic || !a.ContainsKey("device_id")) continue; string id=Convert.ToString(a["device_id"]); if(string.IsNullOrWhiteSpace(id)||id==settings.DeviceId)continue; DeviceInfo d; var isNew=!deviceMap.TryGetValue(id,out d); if(isNew){d=new DeviceInfo{DeviceId=id};deviceMap[id]=d;} var changed=isNew; object raw; var username=a.TryGetValue("username",out raw)&&raw!=null?Convert.ToString(raw):d.Username; if(string.IsNullOrWhiteSpace(username))username="Windows用户"; var ip=r.RemoteEndPoint.Address.ToString(); var mac=a.TryGetValue("mac",out raw)&&raw!=null?Convert.ToString(raw):d.Mac; if(d.Username!=username||d.IP!=ip||d.Mac!=mac)changed=true; d.Username=username; d.IP=ip; d.Mac=mac; bool flag; if(TryReadAnnouncementBool(a,"allow_remote",out flag)){if(d.AllowRemote!=flag)changed=true;d.AllowRemote=flag;} if(TryReadAnnouncementBool(a,"has_app",out flag)){if(d.HasApp!=flag)changed=true;d.HasApp=flag;} if(TryReadAnnouncementBool(a,"has_bat",out flag)){if(d.HasBat!=flag)changed=true;d.HasBat=flag;} d.LastSeen=DateTime.Now; d.IsOnline=true; if(changed)SaveSettingsFile(); Dispatcher.InvokeAsync(RefreshGrid); } catch { if (token.IsCancellationRequested) return; } }
        async Task BroadcastLoop(CancellationToken token) { while (!token.IsCancellationRequested) { await Task.Delay(3000, token).ContinueWith(_ => { }); if (!token.IsCancellationRequested) Broadcast(); } }
        async Task CleanupLoop(CancellationToken token) { while (!token.IsCancellationRequested) { await Task.Delay(4000, token).ContinueWith(_ => { }); bool changed=false; foreach (var d in deviceMap.Values.Where(x => x.IsOnline && (DateTime.Now - x.LastSeen).TotalSeconds > 12)) { d.IsOnline=false; d.IsSelected=false; changed=true; Log("设备离线，已取消选择："+d.Username); } if(changed) SaveSettingsFile(); Dispatcher.InvokeAsync(RefreshGrid); } }
        void Broadcast() { if (udp == null) return; var data = Encoding.UTF8.GetBytes(json.Serialize(new { magic = Magic, device_id = settings.DeviceId, username = settings.Username, mac = LocalMac(), allow_remote = settings.AllowRemote, has_app = !string.IsNullOrWhiteSpace(settings.AppPath), has_bat = !string.IsNullOrWhiteSpace(settings.BatPath), command_port = CommandPort })); foreach (var target in BroadcastAddresses()) try { udp.Send(data, data.Length, new IPEndPoint(target, DiscoveryPort)); } catch { } }
        string LocalMac() { var ni=NetworkInterface.GetAllNetworkInterfaces().FirstOrDefault(n=>n.OperationalStatus==OperationalStatus.Up && n.NetworkInterfaceType!=NetworkInterfaceType.Loopback && n.GetPhysicalAddress().GetAddressBytes().Length==6); return ni==null ? "" : ni.GetPhysicalAddress().ToString(); }
        IEnumerable<IPAddress> BroadcastAddresses() { var result = new HashSet<IPAddress> { IPAddress.Broadcast }; foreach (var ni in NetworkInterface.GetAllNetworkInterfaces().Where(n => n.OperationalStatus == OperationalStatus.Up && n.NetworkInterfaceType != NetworkInterfaceType.Loopback)) foreach (var ua in ni.GetIPProperties().UnicastAddresses) if (ua.Address.AddressFamily == AddressFamily.InterNetwork) { byte[] ip = ua.Address.GetAddressBytes(), mask = ua.IPv4Mask.GetAddressBytes(); result.Add(new IPAddress(new byte[] { (byte)(ip[0] | ~mask[0]), (byte)(ip[1] | ~mask[1]), (byte)(ip[2] | ~mask[2]), (byte)(ip[3] | ~mask[3]) })); } return result; }
        async Task AcceptCommands(CancellationToken token) { while (!token.IsCancellationRequested) try { var client = await listener.AcceptTcpClientAsync(); _ = HandleCommand(client); } catch { if (token.IsCancellationRequested) return; } }
        async Task HandleCommand(TcpClient client) { using (client) using (var stream = client.GetStream()) { try { var senderIp=((IPEndPoint)client.Client.RemoteEndPoint).Address.ToString(); var sender=deviceMap.Values.FirstOrDefault(x=>x.IP==senderIp); var senderName=sender==null ? "未知设备" : sender.Username; var nonce = Convert.ToBase64String(RandomBytes(32)); await WriteJson(stream, new { nonce }); var request = await ReadJson(stream); if ((string)Get(request,"magic") != Magic || (string)Get(request,"target_id") != settings.DeviceId) { await WriteJson(stream,new { ok=false,message="目标设备不匹配"}); return; } if (!settings.AllowRemote || string.IsNullOrWhiteSpace(settings.Password)) { await WriteJson(stream,new { ok=false,message="目标设备未开启远程控制"}); return; } string action=(string)Get(request,"action"), proof=(string)Get(request,"proof"), command=(string)Get(request,"command")??""; if (!FixedEquals(proof, Proof(settings.Password,nonce,settings.DeviceId,action,command))) { Log("拒绝来自 "+senderName+" ("+senderIp+") 的请求：控制口令错误"); await WriteJson(stream,new {ok=false,message="控制口令错误"}); return; } if (action!="shutdown" && action!="reboot" && action!="restart_app" && action!="run_bat" && action!="cmd" && action!="distribution" && action!="distribution_status") { await WriteJson(stream,new {ok=false,message="不支持的操作"}); return; } if (action=="restart_app" && string.IsNullOrWhiteSpace(settings.AppPath)) { await WriteJson(stream,new {ok=false,message="目标设备未配置应用路径"}); return; } if (action=="run_bat" && (string.IsNullOrWhiteSpace(settings.BatPath) || !File.Exists(settings.BatPath))) { await WriteJson(stream,new {ok=false,message="目标设备未配置有效的 BAT 路径"}); return; } if (action=="cmd" && string.IsNullOrWhiteSpace(command)) { await WriteJson(stream,new {ok=false,message="CMD 命令不能为空"}); return; } if (action=="cmd" && IsForbiddenCmd(command)) { Log("拒绝来自 "+senderName+" ("+senderIp+") 的删除类 CMD："+command); await WriteJson(stream,new {ok=false,message="安全策略禁止执行删除类 CMD 指令"}); return; } await WriteJson(stream,new {ok=true,message="命令已接受"}); if(action=="distribution_status") { if(sender!=null)UpdateDistributionProgress(sender,command); return; } Log("来自 "+senderName+" ("+senderIp+") 的 "+ActionName(action)+(action=="cmd" ? "："+command : "")); await Task.Delay(350); if(action=="distribution") await AcceptDistributionAsync(command); else ExecuteAction(action,command); } catch { } } }
        async Task<Dictionary<string,object>> ReadJson(NetworkStream s) { var buffer=new byte[4096]; int n=await s.ReadAsync(buffer,0,buffer.Length); return json.Deserialize<Dictionary<string,object>>(Encoding.UTF8.GetString(buffer,0,n)); }
        async Task WriteJson(NetworkStream s, object o) { var b=Encoding.UTF8.GetBytes(json.Serialize(o)); await s.WriteAsync(b,0,b.Length); }
        object Get(Dictionary<string,object> d,string key) { object v; return d.TryGetValue(key,out v)?v:null; }
        static byte[] RandomBytes(int n) { var b=new byte[n]; using(var r=RandomNumberGenerator.Create()) r.GetBytes(b); return b; }
        static string Proof(string password,string nonce,string target,string action,string command="") { using(var h=new HMACSHA256(Encoding.UTF8.GetBytes(password))) return Convert.ToBase64String(h.ComputeHash(Encoding.UTF8.GetBytes(nonce+"\0"+target+"\0"+action+"\0"+(command??"")))); }
        static bool FixedEquals(string a,string b) { if(a==null||b==null)return false; var x=Encoding.UTF8.GetBytes(a); var y=Encoding.UTF8.GetBytes(b); if(x.Length!=y.Length)return false; int diff=0; for(int i=0;i<x.Length;i++)diff|=x[i]^y[i]; return diff==0; }
        static bool IsForbiddenCmd(string command) { return Regex.IsMatch(command??"",@"(?i)\b(del|erase|rd|rmdir|remove-item|rm|format|diskpart|clear-recyclebin|forfiles)\b"); }
        void ExecuteAction(string action,string command="") { try { if(action=="shutdown") Process.Start(new ProcessStartInfo("shutdown.exe","/s /t 5 /c \"局域网控制工具发起关机\""){UseShellExecute=false,CreateNoWindow=true}); else if(action=="reboot") Process.Start(new ProcessStartInfo("shutdown.exe","/r /t 5 /c \"局域网控制工具发起重启\""){UseShellExecute=false,CreateNoWindow=true}); else if(action=="cmd") Process.Start(new ProcessStartInfo("cmd.exe","/c "+command){UseShellExecute=false,CreateNoWindow=true}); else if(action=="run_bat") Process.Start(new ProcessStartInfo(settings.BatPath){WorkingDirectory=Path.GetDirectoryName(settings.BatPath),UseShellExecute=true}); else { if(!File.Exists(settings.AppPath)) throw new FileNotFoundException("应用不存在",settings.AppPath); try { Process.Start(new ProcessStartInfo("taskkill.exe","/F /IM \""+Path.GetFileName(settings.AppPath)+"\""){UseShellExecute=false,CreateNoWindow=true}).WaitForExit(4000); } catch {} Process.Start(new ProcessStartInfo(settings.AppPath){WorkingDirectory=Path.GetDirectoryName(settings.AppPath),UseShellExecute=true}); } Log("已执行："+ActionName(action)+(action=="cmd" ? "："+command : "")); } catch(Exception ex) { Log("执行失败："+ex.Message); } }
        void RefreshGrid() { var selected=devices.Where(x=>x.IsSelected).Select(x=>x.DeviceId).ToHashSet(); devices.Clear(); foreach(var d in deviceMap.Values.OrderByDescending(x=>x.IsOnline).ThenBy(x=>x.Username).ThenBy(x=>x.IP)) { d.IsSelected=d.IsOnline&&selected.Contains(d.DeviceId); devices.Add(d); } UpdateSelectionText(); }
        void UpdateSelectionText() { var selected=devices.Count(x=>x.IsSelected&&x.IsOnline); SelectionHeaderText.Text=selected+" 台设备已选择"; OnlineText.Text=deviceMap.Values.Count(x=>x.IsOnline)+" 台设备在线 · "+devices.Count+" 台已保存"; DistributionHintText.Text=selected>0 ? "将发送到 "+selected+" 台已选择设备" : "请在左侧选择接收设备"; }
        void SetStatus(string text) { Dispatcher.InvokeAsync(()=>Title="摩诘创新 MoreGet"+text); }
        void Log(string message) { Dispatcher.InvokeAsync(()=> { var now=DateTime.Now; var line=now.ToString("HH:mm:ss")+"  "+message; lock(logLock) { logs.Add(line); if(logs.Count>300) logs.RemoveAt(0); LogBox.Text=string.Join(Environment.NewLine,logs); LogBox.ScrollToEnd(); try { var folder=string.IsNullOrWhiteSpace(settings.LogFolder) ? DefaultLogFolder : settings.LogFolder; Directory.CreateDirectory(folder); File.AppendAllText(Path.Combine(folder,now.ToString("yyyy-MM-dd")+".log"),now.ToString("yyyy-MM-dd HH:mm:ss")+"  "+message+Environment.NewLine,new UTF8Encoding(false)); } catch { } } }); }
        void Refresh_Click(object s, RoutedEventArgs e) { Broadcast(); Log("已发送设备发现广播"); }
        void SelectAll_Click(object s, RoutedEventArgs e) { var online=devices.Where(x=>x.IsOnline).ToList(); bool all=online.Count>0&&online.All(x=>x.IsSelected); foreach(var d in online)d.IsSelected=!all; foreach(var d in devices.Where(x=>!x.IsOnline))d.IsSelected=false; DeviceGrid.Items.Refresh(); UpdateSelectionText(); }
        void Save_Click(object s, RoutedEventArgs e) { if(string.IsNullOrWhiteSpace(UsernameBox.Text)){MessageBox.Show("用户名不能为空。","设置不完整");return;} if(AllowCheck.IsChecked==true&&string.IsNullOrWhiteSpace(PasswordBox.Password)){MessageBox.Show("开启远程控制前必须设置控制口令。","设置不完整");return;} var logFolder=LogFolderBox.Text.Trim(); var distributionFolder=DistributionFolderBox.Text.Trim(); if(string.IsNullOrWhiteSpace(logFolder)||string.IsNullOrWhiteSpace(distributionFolder)){MessageBox.Show("请选择日志保存文件夹和文件分发接收路径。","设置不完整");return;} try { Directory.CreateDirectory(logFolder); Directory.CreateDirectory(distributionFolder); } catch(Exception ex) { MessageBox.Show("无法创建保存文件夹："+ex.Message,"设置不完整");return; } settings.Username=UsernameBox.Text.Trim(); settings.Password=PasswordBox.Password.Trim(); settings.AppPath=AppPathBox.Text.Trim(); settings.BatPath=BatPathBox.Text.Trim(); settings.LogFolder=logFolder; settings.DistributionFolder=distributionFolder; settings.AllowRemote=AllowCheck.IsChecked==true; settings.AutoHide=AutoHideCheck.IsChecked==true; if(!SaveSettingsFile()){MessageBox.Show("配置保存失败，原配置文件未被覆盖。\n\n"+settingsSaveError,"保存失败",MessageBoxButton.OK,MessageBoxImage.Error);return;} Broadcast(); Log("设置已保存，接收路径："+settings.DistributionFolder); AppDrawerHost.IsLeftDrawerOpen=false; MessageBox.Show("设置已保存。","局域网控制工具"); }
        void Browse_Click(object s, RoutedEventArgs e) { var d=new OpenFileDialog{Filter="可执行程序 (*.exe)|*.exe|所有文件 (*.*)|*.*"}; if(d.ShowDialog()==true)AppPathBox.Text=d.FileName; }
        void BrowseBat_Click(object s, RoutedEventArgs e) { var d=new OpenFileDialog{Filter="批处理文件 (*.bat;*.cmd)|*.bat;*.cmd|所有文件 (*.*)|*.*"}; if(d.ShowDialog()==true)BatPathBox.Text=d.FileName; }
        void BrowseLogFolder_Click(object s, RoutedEventArgs e) { using(var d=new Forms.FolderBrowserDialog()) { d.Description="选择运行日志保存文件夹"; d.SelectedPath=LogFolderBox.Text; if(d.ShowDialog()==Forms.DialogResult.OK)LogFolderBox.Text=d.SelectedPath; } }
        void BrowseDistributionFolder_Click(object s, RoutedEventArgs e) { using(var d=new Forms.FolderBrowserDialog()) { d.Description="选择文件分发接收路径"; d.SelectedPath=DistributionFolderBox.Text; if(d.ShowDialog()==Forms.DialogResult.OK)DistributionFolderBox.Text=d.SelectedPath; } }
        void RefreshNetworkAdapters_Click(object s,RoutedEventArgs e) { RefreshNetworkAdapters(); }
        void RefreshNetworkAdapters() { var previous=(NetworkAdapterBox.SelectedItem as NetworkAdapterOption)?.Id??settings.LastNetworkAdapterId; var options=new List<NetworkAdapterOption>(); foreach(var adapter in NetworkInterface.GetAllNetworkInterfaces().Where(x=>x.NetworkInterfaceType!=NetworkInterfaceType.Loopback&&x.NetworkInterfaceType!=NetworkInterfaceType.Tunnel)) try { var properties=adapter.GetIPProperties(); var addresses=properties.UnicastAddresses.Where(x=>x.Address.AddressFamily==AddressFamily.InterNetwork&&!IPAddress.IsLoopback(x.Address)).ToList(); var address=addresses.FirstOrDefault(x=>!x.Address.ToString().StartsWith("169.254."))??addresses.FirstOrDefault(); var gateways=properties.GatewayAddresses.Select(x=>x.Address).Where(x=>x.AddressFamily==AddressFamily.InterNetwork&&!x.Equals(IPAddress.Any)).ToList(); var dns=properties.DnsAddresses.Where(x=>x.AddressFamily==AddressFamily.InterNetwork).ToList(); options.Add(new NetworkAdapterOption { Id=adapter.Id,Name=adapter.Name,Description=adapter.Description,DisplayName=adapter.Name+" · "+(adapter.OperationalStatus==OperationalStatus.Up?"已连接":"未连接")+(address==null?"":" · "+address.Address),CurrentAddress=address==null?"":address.Address.ToString(),SubnetMask=address==null||address.IPv4Mask==null?"":address.IPv4Mask.ToString(),Gateway=gateways.Count==0?"":gateways[0].ToString(),PrimaryDns=dns.Count==0?"":dns[0].ToString(),SecondaryDns=dns.Count<2?"":dns[1].ToString() }); } catch{} networkAdapters.Clear(); foreach(var option in options.OrderByDescending(x=>!string.IsNullOrWhiteSpace(x.CurrentAddress)).ThenBy(x=>x.Name))networkAdapters.Add(option); var selected=networkAdapters.FirstOrDefault(x=>x.Id==previous)??networkAdapters.FirstOrDefault(x=>!string.IsNullOrWhiteSpace(x.CurrentAddress))??networkAdapters.FirstOrDefault(); NetworkAdapterBox.SelectedItem=selected; UpdateCurrentNetworkText(); }
        void NetworkAdapterBox_SelectionChanged(object s,System.Windows.Controls.SelectionChangedEventArgs e) { UpdateCurrentNetworkText(); }
        void UpdateCurrentNetworkText() { var adapter=NetworkAdapterBox.SelectedItem as NetworkAdapterOption; CurrentNetworkText.Text=adapter==null?"未找到可用的物理网卡":adapter.CurrentSummary; }
        void LoadCurrentNetwork_Click(object s,RoutedEventArgs e) { var adapter=NetworkAdapterBox.SelectedItem as NetworkAdapterOption; if(adapter==null){MessageBox.Show("请先选择网络适配器。","未选择网卡");return;} IpAddressBox.Text=adapter.CurrentAddress; SubnetMaskBox.Text=string.IsNullOrWhiteSpace(adapter.SubnetMask)?"255.255.255.0":adapter.SubnetMask; GatewayBox.Text=adapter.Gateway; PrimaryDnsBox.Text=adapter.PrimaryDns; SecondaryDnsBox.Text=adapter.SecondaryDns; }
        bool TryParseIpv4(string text,bool optional,string label,out IPAddress address,out string error) { address=null; error=null; text=(text??"").Trim(); if(optional&&text.Length==0)return true; if(!IPAddress.TryParse(text,out address)||address.AddressFamily!=AddressFamily.InterNetwork){error=label+"格式不正确。";return false;} return true; }
        static uint IPv4Number(IPAddress address) { var bytes=address.GetAddressBytes(); return ((uint)bytes[0]<<24)|((uint)bytes[1]<<16)|((uint)bytes[2]<<8)|bytes[3]; }
        bool TryBuildIpProfile(bool requireName,out SavedIpProfile profile,out NetworkAdapterOption adapter,out string error) { profile=null; adapter=NetworkAdapterBox.SelectedItem as NetworkAdapterOption; error=null; if(adapter==null){error="请先选择需要修改的网络适配器。";return false;} var name=IpProfileNameBox.Text.Trim(); if(requireName&&string.IsNullOrWhiteSpace(name)){error="请输入常用 IP 配置名称。";return false;} IPAddress ip,mask,gateway,dns1,dns2; if(!TryParseIpv4(IpAddressBox.Text,false,"IPv4 地址",out ip,out error)||!TryParseIpv4(SubnetMaskBox.Text,false,"子网掩码",out mask,out error)||!TryParseIpv4(GatewayBox.Text,true,"默认网关",out gateway,out error)||!TryParseIpv4(PrimaryDnsBox.Text,true,"首选 DNS",out dns1,out error)||!TryParseIpv4(SecondaryDnsBox.Text,true,"备用 DNS",out dns2,out error))return false; var ipValue=IPv4Number(ip); var maskValue=IPv4Number(mask); var inverse=~maskValue; if(maskValue==0||(inverse&(inverse+1))!=0){error="子网掩码不是有效的连续掩码。";return false;} var network=ipValue&maskValue; var broadcast=network|inverse; if(ipValue==network||ipValue==broadcast){error="IPv4 地址不能是当前子网的网络地址或广播地址。";return false;} if(gateway!=null&&(IPv4Number(gateway)&maskValue)!=network){error="默认网关必须与 IPv4 地址位于同一子网。";return false;} if(dns2!=null&&dns1==null){error="填写备用 DNS 前需要先填写首选 DNS。";return false;} profile=new SavedIpProfile { Id=Guid.NewGuid().ToString("N"),Name=string.IsNullOrWhiteSpace(name)?ip.ToString():name,AdapterId=adapter.Id,AdapterName=adapter.Name,IPAddress=ip.ToString(),SubnetMask=mask.ToString(),Gateway=gateway==null?"":gateway.ToString(),PrimaryDns=dns1==null?"":dns1.ToString(),SecondaryDns=dns2==null?"":dns2.ToString() }; return true; }
        bool ValidateIpProfile(SavedIpProfile profile,out IPAddress target,out string error) { target=null; error=null; IPAddress mask,gateway,dns1,dns2; if(profile==null){error="IP 配置不存在。";return false;} if(!TryParseIpv4(profile.IPAddress,false,"IPv4 地址",out target,out error)||!TryParseIpv4(profile.SubnetMask,false,"子网掩码",out mask,out error)||!TryParseIpv4(profile.Gateway,true,"默认网关",out gateway,out error)||!TryParseIpv4(profile.PrimaryDns,true,"首选 DNS",out dns1,out error)||!TryParseIpv4(profile.SecondaryDns,true,"备用 DNS",out dns2,out error))return false; var ipValue=IPv4Number(target); var maskValue=IPv4Number(mask); var inverse=~maskValue; if(maskValue==0||(inverse&(inverse+1))!=0){error="子网掩码不是有效的连续掩码。";return false;} var network=ipValue&maskValue; if(ipValue==network||ipValue==(network|inverse)){error="IPv4 地址不能是当前子网的网络地址或广播地址。";return false;} if(gateway!=null&&(IPv4Number(gateway)&maskValue)!=network){error="默认网关必须与 IPv4 地址位于同一子网。";return false;} if(dns2!=null&&dns1==null){error="填写备用 DNS 前需要先填写首选 DNS。";return false;} return true; }
        void AddIpProfile_Click(object s,RoutedEventArgs e) { SavedIpProfile profile; NetworkAdapterOption adapter; string error; if(!TryBuildIpProfile(true,out profile,out adapter,out error)){MessageBox.Show(error,"配置不完整",MessageBoxButton.OK,MessageBoxImage.Warning);return;} var existing=ipProfiles.FirstOrDefault(x=>string.Equals(x.Name,profile.Name,StringComparison.OrdinalIgnoreCase)); var replacedIndex=-1; if(existing!=null){profile.Id=existing.Id; replacedIndex=ipProfiles.IndexOf(existing); ipProfiles[replacedIndex]=profile;}else ipProfiles.Add(profile); if(!SaveSettingsFile()){if(existing==null)ipProfiles.Remove(profile);else ipProfiles[replacedIndex]=existing;MessageBox.Show("常用 IP 保存失败："+settingsSaveError,"保存失败",MessageBoxButton.OK,MessageBoxImage.Error);return;} IpProfileList.Items.Refresh(); Log("已保存常用 IP 配置："+profile.Name); }
        async void ApplyEditorIp_Click(object s,RoutedEventArgs e) { SavedIpProfile profile; NetworkAdapterOption adapter; string error; if(!TryBuildIpProfile(false,out profile,out adapter,out error)){MessageBox.Show(error,"配置不完整",MessageBoxButton.OK,MessageBoxImage.Warning);return;} await ApplyIpConfigurationAsync(profile,adapter); }
        async void ApplyIpProfile_Click(object s,RoutedEventArgs e) { var profile=(s as FrameworkElement)?.Tag as SavedIpProfile; if(profile==null)return; RefreshNetworkAdapters(); var adapter=networkAdapters.FirstOrDefault(x=>x.Id==profile.AdapterId)??networkAdapters.FirstOrDefault(x=>string.Equals(x.Name,profile.AdapterName,StringComparison.OrdinalIgnoreCase)); if(adapter==null){MessageBox.Show("配置绑定的网卡“"+profile.AdapterName+"”当前不存在。","无法切换 IP",MessageBoxButton.OK,MessageBoxImage.Warning);return;} NetworkAdapterBox.SelectedItem=adapter; await ApplyIpConfigurationAsync(profile,adapter); }
        void DeleteIpProfile_Click(object s,RoutedEventArgs e) { var profile=(s as FrameworkElement)?.Tag as SavedIpProfile; if(profile==null)return; if(MessageBox.Show("确定删除常用 IP 配置“"+profile.Name+"”吗？","删除常用 IP",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return; ipProfiles.Remove(profile); if(!SaveSettingsFile())MessageBox.Show("删除未能保存："+settingsSaveError,"保存失败",MessageBoxButton.OK,MessageBoxImage.Error); }
        async Task<string> DetectIpConflictAsync(IPAddress target,NetworkAdapterOption selectedAdapter) { var selectedOwnsAddress=false; var canUseArp=false; var targetValue=IPv4Number(target); foreach(var adapter in NetworkInterface.GetAllNetworkInterfaces())try { foreach(var address in adapter.GetIPProperties().UnicastAddresses.Where(x=>x.Address.AddressFamily==AddressFamily.InterNetwork)) { if(address.Address.Equals(target)){if(adapter.Id!=selectedAdapter.Id)return "该地址已被本机网卡“"+adapter.Name+"”使用。";selectedOwnsAddress=true;} if(address.IPv4Mask!=null&&(targetValue&IPv4Number(address.IPv4Mask))==(IPv4Number(address.Address)&IPv4Number(address.IPv4Mask)))canUseArp=true; } } catch{} if(selectedOwnsAddress)return null; byte[] discoveredMac=null; if(canUseArp)await Task.Run(()=> { try { var buffer=new byte[8]; var length=buffer.Length; if(SendARP(BitConverter.ToInt32(target.GetAddressBytes(),0),0,buffer,ref length)==0&&length>0)discoveredMac=buffer.Take(length).ToArray(); } catch{} }); if(discoveredMac!=null) { var mac=string.Join("-",discoveredMac.Select(x=>x.ToString("X2"))); return "局域网内已有设备响应此 IP（MAC："+mac+"）。"; } try { using(var ping=new Ping())for(var attempt=0;attempt<2;attempt++){var reply=await ping.SendPingAsync(target,600);if(reply.Status==IPStatus.Success)return "局域网内已有设备响应此 IP 的 Ping 请求。";} } catch{} return null; }
        static string PowerShellQuote(string value) { return "'"+(value??"").Replace("'","''")+"'"; }
        async Task<int> RunElevatedNetworkCommandAsync(IEnumerable<string> commands) { var script="$ErrorActionPreference='Stop'; "+string.Join("; ",commands.Select(x=>x+"; if($LASTEXITCODE -ne 0){exit $LASTEXITCODE}")); var encoded=Convert.ToBase64String(Encoding.Unicode.GetBytes(script)); var process=Process.Start(new ProcessStartInfo { FileName="powershell.exe",Arguments="-NoProfile -NonInteractive -ExecutionPolicy Bypass -EncodedCommand "+encoded,Verb="runas",UseShellExecute=true,WindowStyle=ProcessWindowStyle.Hidden }); await Task.Run(()=>process.WaitForExit()); return process.ExitCode; }
        async Task ApplyIpConfigurationAsync(SavedIpProfile profile,NetworkAdapterOption adapter) { IPAddress target; string validationError; if(!ValidateIpProfile(profile,out target,out validationError)){MessageBox.Show(validationError,"IP 配置无效",MessageBoxButton.OK,MessageBoxImage.Error);return;} try { CurrentNetworkText.Text="正在检测 "+profile.IPAddress+" 是否冲突…"; var conflict=await DetectIpConflictAsync(target,adapter); UpdateCurrentNetworkText(); if(conflict!=null){MessageBox.Show("为避免网络中断，已取消切换。\n\n"+conflict,"检测到 IP 冲突",MessageBoxButton.OK,MessageBoxImage.Error);Log("IP 切换已取消，检测到冲突："+profile.IPAddress);return;} var details=profile.IPAddress+" / "+profile.SubnetMask+(string.IsNullOrWhiteSpace(profile.Gateway)?"":"\n网关："+profile.Gateway)+(string.IsNullOrWhiteSpace(profile.PrimaryDns)?"":"\nDNS："+profile.PrimaryDns+(string.IsNullOrWhiteSpace(profile.SecondaryDns)?"":"、"+profile.SecondaryDns)); if(MessageBox.Show("未检测到 IP 冲突。确定修改网卡“"+adapter.Name+"”吗？\n\n"+details+"\n\n切换过程中网络会短暂中断。","确认切换本机 IP",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return; var adapterArgument="name="+PowerShellQuote(adapter.Name); var gateway=string.IsNullOrWhiteSpace(profile.Gateway)?"none":profile.Gateway; var commands=new List<string>{"& $env:SystemRoot\\System32\\netsh.exe interface ipv4 set address "+adapterArgument+" source=static address="+profile.IPAddress+" mask="+profile.SubnetMask+" gateway="+gateway+(gateway=="none"?"":" gwmetric=1")+" store=persistent"}; if(!string.IsNullOrWhiteSpace(profile.PrimaryDns)){commands.Add("& $env:SystemRoot\\System32\\netsh.exe interface ipv4 set dnsservers "+adapterArgument+" source=static address="+profile.PrimaryDns+" register=primary validate=no");if(!string.IsNullOrWhiteSpace(profile.SecondaryDns))commands.Add("& $env:SystemRoot\\System32\\netsh.exe interface ipv4 add dnsservers "+adapterArgument+" address="+profile.SecondaryDns+" index=2 validate=no");} var exitCode=await RunElevatedNetworkCommandAsync(commands); if(exitCode!=0)throw new Exception("系统网络配置命令返回错误代码 "+exitCode+"。"); await Task.Delay(1500); RefreshNetworkAdapters(); Broadcast(); Log("已将网卡 "+adapter.Name+" 切换为 "+profile.IPAddress); MessageBox.Show("IP 配置已应用。","切换完成",MessageBoxButton.OK,MessageBoxImage.Information); } catch(System.ComponentModel.Win32Exception ex) when(ex.NativeErrorCode==1223) { UpdateCurrentNetworkText(); MessageBox.Show("已取消管理员授权，IP 配置没有更改。","操作已取消",MessageBoxButton.OK,MessageBoxImage.Information); } catch(Exception ex) { UpdateCurrentNetworkText(); MessageBox.Show("切换失败："+ex.Message,"无法修改 IP",MessageBoxButton.OK,MessageBoxImage.Error);Log("IP 切换失败："+ex.Message); } }
        async void EnableDhcp_Click(object s,RoutedEventArgs e) { var adapter=NetworkAdapterBox.SelectedItem as NetworkAdapterOption; if(adapter==null){MessageBox.Show("请先选择网络适配器。","未选择网卡");return;} if(MessageBox.Show("确定将网卡“"+adapter.Name+"”恢复为自动获取 IP 和 DNS 吗？\n\n网络会短暂中断。","恢复 DHCP",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return; try { var adapterArgument="name="+PowerShellQuote(adapter.Name); var exitCode=await RunElevatedNetworkCommandAsync(new[]{"& $env:SystemRoot\\System32\\netsh.exe interface ipv4 set address "+adapterArgument+" source=dhcp","& $env:SystemRoot\\System32\\netsh.exe interface ipv4 set dnsservers "+adapterArgument+" source=dhcp"}); if(exitCode!=0)throw new Exception("系统网络配置命令返回错误代码 "+exitCode+"。"); await Task.Delay(1800); RefreshNetworkAdapters(); Broadcast(); Log("已将网卡 "+adapter.Name+" 恢复为 DHCP"); MessageBox.Show("已恢复自动获取 IP 和 DNS。","DHCP 已启用",MessageBoxButton.OK,MessageBoxImage.Information); } catch(System.ComponentModel.Win32Exception ex) when(ex.NativeErrorCode==1223) { MessageBox.Show("已取消管理员授权，网络配置没有更改。","操作已取消",MessageBoxButton.OK,MessageBoxImage.Information); } catch(Exception ex) { MessageBox.Show("恢复 DHCP 失败："+ex.Message,"网络配置失败",MessageBoxButton.OK,MessageBoxImage.Error);Log("恢复 DHCP 失败："+ex.Message); } }
        bool TryGetDroppedPath(DragEventArgs e,out string path) { path=null; if(!e.Data.GetDataPresent(DataFormats.FileDrop))return false; var paths=e.Data.GetData(DataFormats.FileDrop) as string[]; if(paths==null||paths.Length!=1)return false; path=paths[0]; return File.Exists(path)||Directory.Exists(path); }
        void ShowDropOverlay(DragEventArgs e) { string path; var valid=TryGetDroppedPath(e,out path); var selected=devices.Count(x=>x.IsSelected&&x.IsOnline); DropOverlayTitle.Text=valid ? (selected>0 ? "释放鼠标，立即发送" : "释放鼠标，添加到文件分发") : "一次只能拖入一个文件或文件夹"; DropOverlaySubtitle.Text=valid ? (selected>0 ? "将发送到 "+selected+" 台已选择设备 · 支持单个文件或文件夹" : "添加后，请在左侧选择在线接收设备") : "当前分发任务仅支持一个文件或一个文件夹"; e.Effects=valid ? DragDropEffects.Copy : DragDropEffects.None; if(DropOverlay.Visibility!=Visibility.Visible) { AppDrawerHost.IsLeftDrawerOpen=false; AppDrawerHost.IsRightDrawerOpen=false; WorkspaceContent.Effect=new BlurEffect{Radius=14}; DropOverlay.Visibility=Visibility.Visible; } e.Handled=true; }
        void HideDropOverlay() { DropOverlay.Visibility=Visibility.Collapsed; WorkspaceContent.Effect=null; }
        void Window_DragEnter(object s,DragEventArgs e) { ShowDropOverlay(e); }
        void Window_DragOver(object s,DragEventArgs e) { ShowDropOverlay(e); }
        void Window_DragLeave(object s,DragEventArgs e) { HideDropOverlay(); e.Handled=true; }
        void Window_Drop(object s,DragEventArgs e) { string path; var valid=TryGetDroppedPath(e,out path); HideDropOverlay(); e.Handled=true; if(!valid) { MessageBox.Show("一次只能拖入一个存在的文件或文件夹。","无法添加分发内容",MessageBoxButton.OK,MessageBoxImage.Information); return; } DistributionSourceBox.Text=path; var targets=devices.Where(x=>x.IsSelected&&x.IsOnline).ToList(); if(targets.Any()) { Log("已通过拖放选择分发内容："+path); CreateDistribution_Click(this,new RoutedEventArgs()); } else { DistributionHintText.Text="已添加 "+Path.GetFileName(path.TrimEnd(Path.DirectorySeparatorChar))+" · 请在左侧选择接收设备"; Log("已通过拖放添加分发内容，等待选择接收设备："+path); } }
        void ChooseDistributionFile_Click(object s,RoutedEventArgs e) { var d=new OpenFileDialog{Filter="所有文件 (*.*)|*.*"}; if(d.ShowDialog()==true)DistributionSourceBox.Text=d.FileName; }
        void ChooseDistributionFolder_Click(object s,RoutedEventArgs e) { using(var d=new Forms.FolderBrowserDialog()) { d.Description="选择要分发的文件夹"; if(d.ShowDialog()==Forms.DialogResult.OK)DistributionSourceBox.Text=d.SelectedPath; } }
        async void CreateDistribution_Click(object s,RoutedEventArgs e) { var path=DistributionSourceBox.Text.Trim(); var targets=devices.Where(x=>x.IsSelected && x.IsOnline).ToList(); if(!File.Exists(path) && !Directory.Exists(path)){MessageBox.Show("请选择存在的文件或文件夹。","无法创建任务");return;} if(!targets.Any()){MessageBox.Show("请先在左侧选择至少一台在线接收设备。","未选择设备");return;} try { EnsureDistributionServices(); var task=new DistributionTask{Name=Path.GetFileName(path.TrimEnd(Path.DirectorySeparatorChar)),SourcePath=path,SourceIp=LocalIPv4(),IsReceiving=false,TargetDeviceIds=targets.Select(x=>x.DeviceId).ToList(),Status="正在生成私有 Torrent 元数据"}; distributionTasks.Insert(0,task); distributionMap[task.Id]=task; var folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"LanControlTool","Distribution","Torrents"); Directory.CreateDirectory(folder); var torrentPath=Path.Combine(folder,task.Id+".torrent"); var creator=new TorrentCreator(TorrentType.V1Only){Private=true,CreatedBy="LanControlTool",Comment="仅限局域网控制工具私有分发",Announce="udp://"+task.SourceIp+":6970/announce"}; await creator.CreateAsync(new TorrentFileSource(path),torrentPath); task.TorrentPath=torrentPath; task.TorrentUrl="http://"+task.SourceIp+":45672/torrent/"+task.Id; var torrent=Torrent.Load(torrentPath); var seedPath=File.Exists(path)?Path.GetDirectoryName(path):Path.GetDirectoryName(path.TrimEnd(Path.DirectorySeparatorChar)); var manager=torrentEngine.Contains(torrent) ? torrentEngine.Torrents.FirstOrDefault(x=>x.Torrent!=null && x.Torrent.InfoHashes.Equals(torrent.InfoHashes)) : null; if(manager==null) { manager=await torrentEngine.AddAsync(torrent,seedPath); await manager.StartAsync(); } distributionManagers[task.Id]=manager; task.HasTransferManager=true; task.Status="正在做种并发送给 "+targets.Count+" 台设备"; task.Raise("Status"); foreach(var target in targets)_=SendDistributionOffer(target,task); DistributionTaskList.Items.Refresh(); Log("已发布文件分发任务："+task.Name+"，目标 "+targets.Count+" 台设备"); MessageBox.Show("任务已发布。目标设备收到任务后将自动加入局域网 P2P 分发。","文件分发",MessageBoxButton.OK,MessageBoxImage.Information); } catch(Exception ex) { MessageBox.Show(ex.Message,"创建 Torrent 失败",MessageBoxButton.OK,MessageBoxImage.Error); Log("创建文件分发任务失败："+ex.ToString()); } }
        void EnsureDistributionServices() { if(torrentEngine==null) torrentEngine=new ClientEngine(new EngineSettingsBuilder{AllowPortForwarding=false,AllowLocalPeerDiscovery=false,AutoSaveLoadDhtCache=false,AutoSaveLoadFastResume=true,MaximumConnections=80}.ToSettings()); if(torrentTrackerListener==null) { var tracker=new TrackerServer{AllowUnregisteredTorrents=true,AllowScrape=false}; var trackerListener=TrackerListenerFactory.CreateUdp(IPAddress.Any,6970); tracker.RegisterListener(trackerListener); trackerListener.Start(); torrentTracker=tracker; torrentTrackerListener=trackerListener; } if(distributionMetadataListener==null) { distributionMetadataListener=new TcpListener(IPAddress.Any,45672); distributionMetadataListener.Start(); _=ServeDistributionMetadata(); } }
        async Task ServeDistributionMetadata() { while(distributionMetadataListener!=null) try { var client=await distributionMetadataListener.AcceptTcpClientAsync(); _=SendDistributionMetadata(client); } catch { return; } }
        async Task SendDistributionMetadata(TcpClient client) { using(client) using(var stream=client.GetStream()) { try { var buffer=new byte[2048]; var count=await stream.ReadAsync(buffer,0,buffer.Length); var request=Encoding.ASCII.GetString(buffer,0,count); var first=request.Split('\n').FirstOrDefault()??""; var path=first.Split(' ').Skip(1).FirstOrDefault()??""; var id=path.Split('?')[0].Trim('/').Split('/').LastOrDefault(); DistributionTask task; if(id!=null && distributionMap.TryGetValue(id,out task) && File.Exists(task.TorrentPath)) { var bytes=File.ReadAllBytes(task.TorrentPath); var header=Encoding.ASCII.GetBytes("HTTP/1.1 200 OK\r\nContent-Type: application/x-bittorrent\r\nContent-Length: "+bytes.Length+"\r\nConnection: close\r\n\r\n"); await stream.WriteAsync(header,0,header.Length); await stream.WriteAsync(bytes,0,bytes.Length); } else { var header=Encoding.ASCII.GetBytes("HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\nConnection: close\r\n\r\n"); await stream.WriteAsync(header,0,header.Length); } } catch { } } }
        async Task SendDistributionOffer(DeviceInfo d,DistributionTask task) { var result=await SendCommand(d,"distribution",PasswordBox.Password.Trim(),task.Id+"|"+task.TorrentUrl); if(result.Success)Log("已向 "+d.Username+" 发送分发任务："+task.Name); }
        async Task AcceptDistributionAsync(string value) { var parts=value.Split(new[]{'|'},2); if(parts.Length!=2)throw new Exception("分发任务格式错误"); var localTask=new DistributionTask{Id=parts[0],Name="正在接收分发任务",SourcePath=settings.DistributionFolder,IsReceiving=true,Status="正在接收 Torrent 元数据",PeerSummary="等待发布端提供元数据"}; distributionMap[localTask.Id]=localTask; await Dispatcher.InvokeAsync(()=>{ distributionTasks.Insert(0,localTask); DistributionTaskList.Items.Refresh(); }); try { if(torrentEngine==null)torrentEngine=new ClientEngine(new EngineSettingsBuilder{AllowPortForwarding=false,AllowLocalPeerDiscovery=false,AutoSaveLoadDhtCache=false,AutoSaveLoadFastResume=true,MaximumConnections=80}.ToSettings()); var folder=string.IsNullOrWhiteSpace(settings.DistributionFolder)?DefaultDistributionFolder:settings.DistributionFolder; var metadata=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"LanControlTool","Distribution","Torrents",parts[0]+".torrent"); Directory.CreateDirectory(folder); Directory.CreateDirectory(Path.GetDirectoryName(metadata)); using(var wc=new System.Net.WebClient())await wc.DownloadFileTaskAsync(new Uri(parts[1]),metadata); var torrent=Torrent.Load(metadata); localTask.Name=torrent.Name; localTask.SourcePath=folder; localTask.Status="正在加入 P2P 下载"; localTask.Raise("Name"); localTask.Raise("Status"); await Dispatcher.InvokeAsync(()=>DistributionTaskList.Items.Refresh()); var manager=torrentEngine.Contains(torrent) ? torrentEngine.Torrents.FirstOrDefault(x=>x.Torrent!=null && x.Torrent.InfoHashes.Equals(torrent.InfoHashes)) : null; if(manager==null) { manager=await torrentEngine.AddAsync(metadata,folder); await manager.StartAsync(); } distributionManagers[localTask.Id]=manager; localTask.HasTransferManager=true; _=ReportDistributionProgress(parts[0],new Uri(parts[1]).Host,manager); Log("已接收并开始下载文件分发任务："+torrent.Name+"，保存到："+folder); } catch(Exception ex) { localTask.Status="接收失败："+ex.Message; localTask.PeerSummary="请检查发布端是否在线、防火墙及接收路径空间"; localTask.Raise("Status"); localTask.Raise("PeerSummary"); await Dispatcher.InvokeAsync(()=>DistributionTaskList.Items.Refresh()); throw; } }
        async Task ReportDistributionProgress(string taskId,string sourceIp,TorrentManager manager) { while(manager!=null) { try { DistributionTask localTask; var complete=manager.Complete; if(distributionMap.TryGetValue(taskId,out localTask)) { localTask.IsTransferComplete=complete; if(complete) { localTask.IsPaused=false; localTask.Status="下载完成，正在做种（点击卡片打开文件夹）"; } else localTask.Status=localTask.IsPaused ? "下载已停止，可继续 · "+manager.Progress.ToString("F1")+"%" : "下载中 · "+manager.Progress.ToString("F1")+"%"; localTask.PeerSummary="↓ "+(manager.Monitor.DownloadRate/1024.0/1024.0).ToString("F2")+" MB/s   ↑ "+(manager.Monitor.UploadRate/1024.0/1024.0).ToString("F2")+" MB/s"; localTask.Raise("Status"); localTask.Raise("PeerSummary"); await Dispatcher.InvokeAsync(()=>DistributionTaskList.Items.Refresh()); } var source=deviceMap.Values.FirstOrDefault(x=>x.IP==sourceIp); if(source!=null) { var value=taskId+"|"+manager.Progress.ToString("F2",System.Globalization.CultureInfo.InvariantCulture)+"|"+manager.State+"|"+manager.Monitor.DownloadRate+"|"+manager.Monitor.UploadRate; await SendCommand(source,"distribution_status",PasswordBox.Password.Trim(),value); } if(complete) return; await Task.Delay(3000); } catch { return; } } }
        void UpdateDistributionProgress(DeviceInfo sender,string value) { var p=value.Split('|'); if(p.Length<5)return; DistributionTask task; if(!distributionMap.TryGetValue(p[0],out task))return; double progress; long download,upload; double.TryParse(p[1],System.Globalization.NumberStyles.Any,System.Globalization.CultureInfo.InvariantCulture,out progress); long.TryParse(p[3],out download); long.TryParse(p[4],out upload); var peers=distributionPeers.GetOrAdd(task.Id,_=>new ConcurrentDictionary<string,DistributionPeerStatus>()); peers[sender.DeviceId]=new DistributionPeerStatus{DeviceId=sender.DeviceId,Username=sender.Username,Progress=progress,State=p[2],DownloadRate=download,UploadRate=upload}; var complete=peers.Values.Count(x=>x.Progress>=100); var allComplete=task.TargetDeviceIds.Count>0&&complete>=task.TargetDeviceIds.Count; task.PeerSummary="已完成 "+complete+" / "+task.TargetDeviceIds.Count+" · "+sender.Username+" "+progress.ToString("F1")+"% ↓"+(download/1024.0/1024.0).ToString("F1")+"MB/s"; if(allComplete) { task.IsPaused=false; task.IsTransferComplete=true; task.Status="发送完成"; task.Raise("Status"); } task.Raise("PeerSummary"); Dispatcher.InvokeAsync(()=>DistributionTaskList.Items.Refresh()); }
        async void ToggleDistributionTransfer_Click(object s,RoutedEventArgs e) { var task=(s as FrameworkElement)?.DataContext as DistributionTask; if(task==null||task.IsTransferComplete)return; TorrentManager manager; if(!distributionManagers.TryGetValue(task.Id,out manager))return; try { if(task.IsPaused) { await manager.StartAsync(); task.IsPaused=false; task.Status=task.IsReceiving ? "正在继续下载" : "正在继续发送"; Log("已继续"+(task.IsReceiving?"下载：":"发送：")+task.Name); } else { await manager.PauseAsync(); task.IsPaused=true; task.Status=task.IsReceiving ? "下载已停止，可继续" : "发送已停止，可继续"; Log("已停止"+(task.IsReceiving?"下载：":"发送：")+task.Name); } task.Raise("Status"); DistributionTaskList.Items.Refresh(); } catch(Exception ex) { MessageBox.Show(ex.Message,task.IsPaused?"继续任务失败":"停止任务失败",MessageBoxButton.OK,MessageBoxImage.Error); } }
        void DistributionTask_Click(object s,MouseButtonEventArgs e) { var task=(s as FrameworkElement)?.DataContext as DistributionTask; if(task==null||!task.IsReceiving||!task.IsTransferComplete)return; var folder=task.SourcePath; if(!Directory.Exists(folder)){MessageBox.Show("接收文件夹不存在："+folder,"无法打开文件夹",MessageBoxButton.OK,MessageBoxImage.Warning);return;} Process.Start(new ProcessStartInfo("explorer.exe","\""+folder+"\""){UseShellExecute=true}); }
        string LocalIPv4() { var ip=NetworkInterface.GetAllNetworkInterfaces().Where(n=>n.OperationalStatus==OperationalStatus.Up && n.NetworkInterfaceType!=NetworkInterfaceType.Loopback).SelectMany(n=>n.GetIPProperties().UnicastAddresses).Select(x=>x.Address).FirstOrDefault(x=>x.AddressFamily==AddressFamily.InterNetwork && !IPAddress.IsLoopback(x)); return ip==null ? "127.0.0.1" : ip.ToString(); }
        void ShowSettings_Click(object s,RoutedEventArgs e) { AppDrawerHost.IsRightDrawerOpen=false; AppDrawerHost.IsLeftDrawerOpen=true; }
        void CloseSettings_Click(object s,RoutedEventArgs e) { AppDrawerHost.IsLeftDrawerOpen=false; }
        void ShowLogs_Click(object s,RoutedEventArgs e) { AppDrawerHost.IsLeftDrawerOpen=false; AppDrawerHost.IsRightDrawerOpen=true; LogBox.ScrollToEnd(); }
        void CloseLogs_Click(object s,RoutedEventArgs e) { AppDrawerHost.IsRightDrawerOpen=false; }
        void ClearLog_Click(object s, RoutedEventArgs e) { lock(logLock)logs.Clear(); LogBox.Clear(); }
        void DeleteDevice_Click(object s, RoutedEventArgs e) { var item=(s as FrameworkElement)?.Tag as DeviceInfo; if(item==null)return; if(MessageBox.Show("确定删除设备“"+item.Username+"”吗？","删除设备",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return; DeviceInfo ignored; deviceMap.TryRemove(item.DeviceId,out ignored); SaveSettingsFile(); RefreshGrid(); Log("已删除设备："+item.Username); }
        void DeviceCard_Click(object s, MouseButtonEventArgs e) { var item=(s as FrameworkElement)?.DataContext as DeviceInfo; if(item==null||!item.IsOnline)return; item.IsSelected=!item.IsSelected; DeviceGrid.Items.Refresh(); UpdateSelectionText(); }
        async void RestartDeviceApp_Click(object s, RoutedEventArgs e) { var item=(s as FrameworkElement)?.Tag as DeviceInfo; if(item==null)return; var password=PasswordBox.Password.Trim(); if(string.IsNullOrWhiteSpace(password)){MessageBox.Show("请输入与目标设备相同的控制口令。","缺少口令");return;} var result=await SendCommand(item,"restart_app",password); ShowCommandResult("重启应用",new[]{result}); }
        async void RunBat_Click(object s, RoutedEventArgs e) { var item=(s as FrameworkElement)?.Tag as DeviceInfo; if(item==null)return; var password=PasswordBox.Password.Trim(); if(string.IsNullOrWhiteSpace(password)){MessageBox.Show("请输入与目标设备相同的控制口令。","缺少口令");return;} if(MessageBox.Show("确定让“"+item.Username+"”执行其本地已配置的 BAT 文件吗？","确认执行 BAT",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return; var result=await SendCommand(item,"run_bat",password); ShowCommandResult("执行本地 BAT",new[]{result}); }
        void WakeDevice_Click(object s, RoutedEventArgs e) { var item=(s as FrameworkElement)?.Tag as DeviceInfo; if(item==null)return; var mac=(item.Mac??"").Replace(":","").Replace("-","").Trim(); if(mac.Length!=12) { MessageBox.Show("该设备尚未上报有效的网卡 MAC 地址。请先在该设备运行一次本工具并保持在线。","无法发送 WOL",MessageBoxButton.OK,MessageBoxImage.Information); return; } try { var address=Enumerable.Range(0,6).Select(i=>Convert.ToByte(mac.Substring(i*2,2),16)).ToArray(); var packet=new byte[102]; for(int i=0;i<6;i++)packet[i]=0xFF; for(int n=0;n<16;n++)Buffer.BlockCopy(address,0,packet,6+n*6,6); using(var sender=new UdpClient()) { sender.EnableBroadcast=true; foreach(var target in BroadcastAddresses()) sender.Send(packet,packet.Length,new IPEndPoint(target,9)); } Log("已向 "+item.Username+" 发送 WOL 魔术包（"+item.Mac+"）"); MessageBox.Show("已发送开机魔术包。目标设备需在 BIOS/网卡及系统中启用网络唤醒。","远程开机",MessageBoxButton.OK,MessageBoxImage.Information); } catch(Exception ex) { MessageBox.Show(ex.Message,"WOL 发送失败",MessageBoxButton.OK,MessageBoxImage.Error); } }
        void Shutdown_Click(object s,RoutedEventArgs e){Confirm("shutdown");} void Reboot_Click(object s,RoutedEventArgs e){Confirm("reboot");} void RestartApp_Click(object s,RoutedEventArgs e){Confirm("restart_app");} void Command_Click(object s,RoutedEventArgs e){ if(string.IsNullOrWhiteSpace(CmdBox.Text)){MessageBox.Show("请输入要执行的 CMD 命令。","CMD 命令为空");return;} Confirm("cmd",CmdBox.Text.Trim()); }
        async void Confirm(string action,string command="") { var targets=devices.Where(x=>x.IsSelected&&x.IsOnline).ToList(); foreach(var offline in devices.Where(x=>!x.IsOnline&&x.IsSelected))offline.IsSelected=false; if(!targets.Any()){MessageBox.Show("请先选择至少一台在线设备。","未选择设备");return;} if(string.IsNullOrWhiteSpace(PasswordBox.Password)){MessageBox.Show("请输入与目标设备相同的控制口令。","缺少口令");return;} string list=string.Join("\n",targets.Select(x=>"• "+x.Username+" ("+x.IP+")")); var commandText=action=="cmd" ? "\n\nCMD："+command : ""; if(MessageBox.Show("确定对以下 "+targets.Count+" 台设备执行“"+ActionName(action)+"”吗？"+commandText+"\n\n"+list,"确认远程操作",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return; Log("开始"+ActionName(action)+"，共 "+targets.Count+" 台设备"); var results=await Task.WhenAll(targets.Select(d=>SendCommand(d,action,PasswordBox.Password.Trim(),command))); ShowCommandResult(ActionName(action),results); }
        async Task<CommandResult> SendCommand(DeviceInfo d,string action,string password,string command="") { try { using(var c=new TcpClient()) { var connect=c.ConnectAsync(d.IP,CommandPort); if(await Task.WhenAny(connect,Task.Delay(4000))!=connect)throw new Exception("连接超时"); using(var stream=c.GetStream()) { var challenge=await ReadJson(stream); string nonce=(string)Get(challenge,"nonce"); await WriteJson(stream,new {magic=Magic,target_id=d.DeviceId,action=action,command=command??"",proof=Proof(password,nonce,d.DeviceId,action,command)}); var response=await ReadJson(stream); var ok=response.ContainsKey("ok") && response["ok"] is bool && (bool)response["ok"]; if(!ok)throw new Exception((string)Get(response,"message")??"目标设备未确认命令"); } } Log(d.Username+" ("+d.IP+")：目标端已接受命令"); return new CommandResult{Device=d,Success=true,Message="目标端已接受命令"}; } catch(Exception ex) { Log(d.Username+" ("+d.IP+")：操作失败："+ex.Message); return new CommandResult{Device=d,Success=false,Message=ex.Message}; } }
        void ShowCommandResult(string action,IEnumerable<CommandResult> results) { var list=results.ToList(); var failed=list.Where(x=>!x.Success).ToList(); if(!failed.Any()) { MessageBox.Show(action+"命令已成功发送，目标设备已确认接收。","操作成功",MessageBoxButton.OK,MessageBoxImage.Information); return; } var detail=string.Join("\n",failed.Select(x=>"• "+x.Device.Username+"："+x.Message)); var prefix=failed.Count==list.Count ? action+"命令发送失败：" : action+"命令已部分发送成功，失败设备："; MessageBox.Show(prefix+"\n\n"+detail,"操作失败",MessageBoxButton.OK,MessageBoxImage.Warning); }
        static string ActionName(string a) { return a=="shutdown"?"远程关机":a=="reboot"?"重启电脑":a=="cmd"?"执行 CMD":a=="run_bat"?"执行本地 BAT":a=="distribution"?"接收文件分发任务":"重启应用"; }
    }
}
